import os


GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")

#All GPT models
GPT_REQUEST_TIMEOUT = 10
GPT_TEMPERATURE = 0
GPT_MAX_RETRIES = 3

#OpenAI
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL_NAME = "gpt-4o"
OPENAI_MAX_TOKENS = 4096

#Azure
AZURE_GPT4_API_KEY = os.getenv("AZURE_GPT4_API_KEY")
AZURE_GPT4_API_VERSION = "2020-05-06"
AZURE_GPT4_ENDPOINT = os.getenv("AZURE_GPT4_ENDPOINT")
AZURE_GPT4_CHAT_DEPLOYMENT_NAME = os.getenv("AZURE_GPT4_CHAT_DEPLOYMENT_NAME")

#Google
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
GOOGLE_API_MODEL = "gemini-1.5-flash"
